<?php
/*
 Plugin Name: Appfoster
 Plugin URI: https://appfoster.com/appfoster
 Description: This is a test plugin for Appfoster.
 Version: 0.0.1
 Author: Mamta Sharma
 Author URI: https://appfoster.com/mamta
 Text Domain: appf
 Generated By: http://ensuredomains.com
 */

// If this file is called directly, abort. //
define ( 'ROOTDIR', plugin_dir_path ( __FILE__ ) );
if ( ! defined( 'WPINC' ) ) {die;} // end if
define('APPF_CORE_VIEWS',dirname( __FILE__ ).'/assets/views/');
//the following hook creates a page on plguin activation
register_activation_hook ( __FILE__, 'create_appf_pages' );
register_deactivation_hook ( __FILE__, 'delete_appf_pages' );

require_once (APPF_CORE_VIEWS .'/test.php');
require_once (APPF_CORE_VIEWS .'/test_content.php');
// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
    require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}
/********Assign plugin menu***********/
add_action( 'admin_menu', 'appf_menu',99 );
function appf_menu(){
    add_menu_page('App-foster', 'App-foster', 'manage_options', 'app-foster', 'appf_render_page' );
}
function appf_render_page() {
    $file = APPF_CORE_VIEWS."app-foster-home.php";
    include( $file );
}
/**********Enqueuing script and style************/
wp_enqueue_script( 'appf-core-js', dirname( __FILE__ ) . '/assets/js/appf-core.js', array('jquery'), null, false );*/
wp_enqueue_style('appf-core-css', dirname( __FILE__ ) . '/assets/js/appf-core.css', null, false );

/****create page endpoint****/
function create_appf_pages(){
    global $wpdb;
    /**We can create an array of multiple pages here**/
    $pages = array(
        array(
            "slug" => "test",
            "title" => "App foster test page",
            "shortcode" => "[app_foster_test]"
        )
    );
    foreach($pages as $singlePage){
        $getPost = get_page_by_path($singlePage['slug']);
        if(!($getPost->ID)){	//check if these pages exists
            try{
                $singlePage = sanitize_post($singlePage);
                $new_page_id = $wpdb->insert($wpdb->posts,
                    array(
                        'post_title' => $singlePage['title'],
                        'post_type' => 'page',
                        'post_name' => $singlePage['slug'],
                        'post_content' => $singlePage['shortcode'],
                        'post_status' => 'publish'
                    ));
                if(!$new_page_id){
                    throw new Exception("Error Processing Request", 1);
                }else{
                    add_post_meta($wpdb->insert_id,'_wp_page_template', 'template-blank-4.php');
                }
            }catch(Exception $e){
                error_log("Error while creating page :".$singlePage['title'], 3, plugin_dir_path(__FILE__).'error_log.log');
            }
        }
    }
    error_log("all pages created successfully");
    return;
}
function delete_appf_pages(){
    $pages = array(
        array(
            "slug" => "test",
            "title" => "App foster test page",
            "shortcode" => "[app_foster_test]"
        )
    );
    foreach($pages as $singlePage){
        $getPost = get_page_by_path($singlePage['slug']);
        if($getPost->ID != null){
            wp_delete_post($getPost->ID, true );
            delete_post_meta($getPost->ID,true);
        }
    }
}